# Generated by Django 4.1.6 on 2023-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Car image')),
                ('price', models.IntegerField(verbose_name='Car price')),
            ],
        ),
    ]
